name: demo
description: An absolute bare-bones web app.
# version: 1.0.0
#homepage: https://www.example.com
#author: david <email@example.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

#dependencies:
#  path: ^1.4.1

dependencies:
  angular: ^5.0.0
  angular_forms: ^2.0.0
  angular_router: ^2.0.0-alpha+19
  build_runner: any
  build_web_compilers: ^1.0.0
  pedantic: ^1.0.0
  analyzer: ^0.34.3
  test: ^1.5.0