version: '3'
services:
  client:
    image: frontend

    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "8080:80"


  middleman:

    image: middleman
    build:
      context: .
      dockerfile: middleman/Dockerfile
    ports:
      - "8888:8888"
    environment:
      - CAL_DB_HOST=postgres
      - CAL_DB_PORT=5432
      - CAL_DB_USER=docker
      - CAL_DB_NAME=docker
      - CAL_DB_PASS=docker


  postgres:
    image: "postgres"
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_PASSWORD: docker
      POSTGRES_USER: docker
